<?php
if (@$_POST['email'] || @$_POST['token']) {
    require_once __DIR__ . '/lib/sign.php';
    require_once __DIR__ . '/lib/php_mailer/PHPMailerAutoload.php';
    $conf=new \Panggoo\sign_config();
    $sign=new \Panggoo\sign();
    if ($conf->getMysqli()) {
        if (@$_POST['email']) {
            $data['email']=$conf->mysqli->real_escape_string($_POST['email']);
        } else if (@$_POST['token']) {
            $data['token']=$conf->mysqli->real_escape_string($_POST['token']);
        }
//        email config start
        $mail=new PHPMailer();
        $mail->isSMTP();
        $mail->SMTPDebug=0;
        $mail->Debugoutput='html';
        $mail->Host='smtp.yandex.ru';
        $mail->Port='587';
        $mail->SMTPAuth=true;
        $mail->Username='support@panggoo.com';
        $mail->Password='same_password_here';
        $mail->setFrom('support@panggoo.com', 'Panggoo Support');
        $mail->addReplyTo('support@panggoo.com', 'Panggoo Support');
        $mail->AltBody = '';
//        email config end
        if (@$data['email']) {
            if ($conf->getEmail($data['email'])) {
                if ($sign->getSign(null,null,$data['email'])[0]) {
                    $conf->getToken();
                    $conf->getRegDate();
                    if ($sign->getRecovery($sign->user['Id'])) {
                        $request="UPDATE `recovery` SET `token`='{$conf->token}', `date`='{$conf->reg_date}' WHERE `owner`='{$sign->user['Id']}'";
                    } else {
                        $request="INSERT INTO `recovery` (`owner`, `token`, `date`)VALUES('{$sign->user['Id']}', '{$conf->token}', '{$conf->reg_date}')";
                    }
                    if ($conf->mysqli->query($request)) {
//                    email config add start
                        $mail->addAddress($sign->user['email']);
                        $mail->Subject='Panggoo account - Forgotten password';
                        $mail->Body = "Dear {$sign->user['username']},


        This is an automated message generated by Panggoo account system to help you reset your password.
        Please follow to below link to reset your password, if you didn't request a recovery just ignore it.

        http://panggoo.com/recovery?token={$conf->token}


        If you have some question, just send reply to that letter.


                                                                                                Your service of the Panggoo.
        ";
//                    email config add end
                        if ($mail->send()) {
                            $err_log=[0, 'We sent you the recovery link to email'];
                        } else {
                            $err_log=[0, 'Sorry, but we can not to send recovery link ERROR: '.$mail->ErrorInfo];
                        }
                        echo json_encode($err_log);
                    }
                } else {
                    $err_log=[0, 'Email does not exist'];
                    echo json_encode($err_log);
                }
            } else {
                $err_log=[0, 'Some trouble with email, check a format'];
                echo json_encode($err_log);
            }
        } else if (@$data['token']) {
            if ($sign->getRecovery(null, $data['token'])) {
                $code_alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
                $code_alphabet.='abcdefghijklmnopqrstuvwxyz';
                $code_alphabet.='0123456789';
                $code_length=iconv_strlen($code_alphabet, 'UTF-8')-1;
                $new_password='';
                for ($i=0; $i<10; $i++) {
                    $new_password.=$code_alphabet[rand(0, $code_length)];
                }
                if ($conf->getPassword($new_password)) {
                    if (
                        $conf->mysqli->query("UPDATE `account` SET `password`='{$conf->password}' WHERE `Id`={$sign->user['Id']}") &&
                        $conf->mysqli->query("DELETE FROM `recovery` WHERE `owner`={$sign->user['Id']}")) {
//                        email config add start
                        $mail->addAddress($sign->user['email']);
                        $mail->Subject='Panggoo account - New password';
                        $mail->Body = "Dear {$sign->user['username']},


            This is an automated message generated by Panggoo account system to help you reset your password.
            The new password is
                                    {$new_password}.
            You can change it in your profile after Sign In.


            If you have some question, just send reply to that letter.


                                                                                                    Your service of the Panggoo.
            ";
    //                    email config add end
                        if ($mail->send()) {
                            $err_log=[0, 'The new password is '.$new_password.', we sent it you to email, you can change it in profile after Sign In'];
                        } else {
                            $err_log=[0, 'The new password is '.$new_password.', sorry, but we can not to send new password (ERROR: '.$mail->ErrorInfo.'), you can change it in profile after Sign In'];
                        }
                        echo json_encode($err_log);
                    } else {
                        $err_log=[0, 'Sorry system error, try to refresh the page'];
                        echo json_encode($err_log);
                    }
                } else {
                    $err_log=[0, 'Some trouble with system, try again, please'];
                    echo json_encode($err_log);
                }
            } else {
                $err_log=[0, 'Sorry, looks like the link is already used'];
                echo json_encode($err_log);
            }
        }
    }
} else {
    $err_log=[0, 'Fill out all fields, please'];
    echo json_encode($err_log);
}
?>